### ISSUE TITLE
readSafeJSONString returns null

### ISSUE THREAD

**Issue by arnuschky** [kjur/jsjws#10]
This code for decoding a token is directly taken from the demo on the website:

      var a = currentToken.split(".");
      var uHeader = b64utos(a[0]);
      var uClaim = b64utos(a[1]);
      var pHeader = KJUR.jws.JWS.readSafeJSONString(uHeader);
      var pClaim = KJUR.jws.JWS.readSafeJSONString(uClaim);

Problem here is that readSafeJSONString always returns null for a valid json (checked in json lint).  I am using it with

      'vendor/jsrsasign/jsrsasign-4.1.4-all-min.js',
      'vendor/jsjws/jws-3.0.min.js'

Any ideas?

**Comment by kjur** [comment]
Thank you for the report. I've fixed them in the latest 3.2.2 release. Thanks.
