### ISSUE TITLE
Couple implementation to update compassion matrix

### ISSUE THREAD

**Issue by dvsekhvalnov** [kjur/jsjws#11]
Hi Kjur,
 
sorry to contact you here, wasn't able to find email.

Just to add 2 libraries which covers full suite of algorithms to compassion sheet you are maintaining at: http://kjur.github.io/jsjws/index_mat.html

1. https://bitbucket.org/b_c/jose4j/wiki/Home (Java)
2. https://github.com/dvsekhvalnov/jose-jwt (C#)

**Comment by kjur** [comment]
Thanks for the report. I've added your jose-jwt .NET. The jose4j is already added. Regards.
