### ISSUE TITLE
Error in sign function

### ISSUE THREAD

**Issue by olgierds** [kjur/jsjws#12]
Hi,
in both files (full and min) in version 3.0 there is an error:
```javascript
KJUR.jws.JWS.sign = function(alg, sHeader, sPayload, key, pass) {
    var ns1 = KJUR.jws.JWS;

    if (! ns1.isSafeJSONString(sHeader))
	throw "JWS Head is not safe JSON string: " + sHead;
```
the "sHead" should be "sHeader", the same goes to min file there should be "p" instead of "sHead"

**Comment by kjur** [comment]
Thank you for the report. I've fix and push the code. It'll be included in the next release. Thanks.
