### ISSUE TITLE
Error in sign function "JWS Head is not safe JSON string"

### ISSUE THREAD

**Issue by MonkRocker** [kjur/jsjws#14]
My header string is being passed as:

'{"alg": "HS256", "cty": "JWT"}'

which is pasted directly from one of the jsjws tests, AND validates just fine in JSONlint and every other parser I have found,  What is meant by "safe" JSON string in this instance?

**Comment by shea256** [comment]
Yes I got the same error:

> Uncaught JWS Head is not safe JSON string

Any thoughts on this?

**Comment by turimm** [comment]
That's because of  jsjws uses function jsonParse from ./ext/json-sans-eval-min.js so you need to include that script to your page but after it I got ReferenceError: utf8tob64u is not defined and I have no idea how this function could work because it does not exist in project

**Comment by noah-freitas** [comment]
I was able to work around this by including the `./ext/json-sans-eval-min.js` and the https://github.com/kjur/jsrsasign library from the same author.  (I included the `jsrsasign-4.1.4-all-min.js` file from that project.)

**Comment by kjur** [comment]
Now jsjws was merged to jsrsasign 4.8.0. Now one script
http://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js which 
concludes jws and json-sans-eval too is enough for loading scirpt.
