### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by jeremyckahn** [kjur/jsjws#19]
Hello, I have cloned this repo and am trying to run the unit tests locally.  The following files contain failing unit tests:

  * qunit-do-jws-sign.html
  * qunit-do-jws-intdate.html

These tests fail on the latest Chrome, Firefox and Safari.

**Comment by kjur** [comment]
Hi @jeremyckahn , I've fixed for sign in the release 3.2.0 today.
http://kjur.github.io/jsjws/test/qunit-do-jws-sign.html
As for intdate, I'll fix it coming version.
Thanks for your report.

**Comment by jeremyckahn** [comment]
Great, thank you for the update!

**Comment by kjur** [comment]
Hi @jeremyckahn , I've also fixed for intdate.
http://kjur.github.io/jsjws/test/qunit-do-jws-intdate.html
Then, fixes are included in the existing 3.2.0 release.
So, I'll close this ticket. Thanks.
