### ISSUE TITLE
Question: IE support

### ISSUE THREAD

**Issue by jeremyckahn** [kjur/jsjws#20]
Hello, I am evaluating this library for use in a project.  My project requires Internet Explorer 8 support, but the samples (http://kjur.github.io/jsjws/tool_jwt.html and http://kjur.github.io/jsjws/sample_generate.html) do not work in IE8.  What versions of IE does jsjws support?

**Comment by kjur** [comment]
I think jsrsasign/jsjws works fine on IE 8, 11.
I've confirmed it works on IE 11 now.
Could you check QUnit tests for JWS/JWT (i.e. qunit-do-jws*, qunit-do-jwt*)
http://kjur.github.io/jsrsasign/test/
