### ISSUE TITLE
Can someone please explain to me how the user agent's pvk remains a secret?

### ISSUE THREAD

**Issue by kalanbates** [kjur/jsjws#21]
I haven't dug into the implementation yet because failure to retain secrecy of the remote client's private key material would be a non-starter (and that has me skeptical.)

How in the world would you process the private key without loading it into the browser and therefore make it accessible to anyone eavesdropping in that browser's Dev Tools, thereby making the private key public knowledge.

**Comment by ehaskins** [comment]
In order to verify you only need the public key.

The private key is used to sign the JWS, then the public key can be used to verify the owner of the private key signed it.

**Comment by kalanbates** [comment]
So that answers the question without actually answering the question:  this is not intended at all for a locally generated key pair.  The approach completely relies on the consumption of another party's public key and completely relies on the privacy of the private key to be another entity's concern. 

Correct?

**Comment by ehaskins** [comment]
I'm only using this for validating a JWS generated by an OpenID Connect server, so I can't speak to other cases, but for that, yes I just need the public key. 

And, yes, just like any other asymmetrical encryption, the owner of the private key must protect it.

**Comment by kalanbates** [comment]
` just like any other asymmetrical encryption, the owner of the private key must protect it.
That was the basis of the question, and the answer seems to be the obvious one: you must rely on some other method  for communicating sensitive data from server to client or for signing data on the client.

I was curious if anyone had somehow been able to maintain confidentiality of the client's private key in a browser, which I had always assumed to be an impossible goal.
