### ISSUE TITLE
JWT Verification Invalid

### ISSUE THREAD

**Issue by iamrameshkr** [kjur/jsjws#22]
Generated JWT using,
http://kjur.github.io/jsjws/tool_jwt.html

But, unable to verify the same using secret,
http://jwt.io/

**Comment by davesbrown** [comment]
I am having the same problem, the two are creating different signatures, but the header and payloads are the same.  I'm trying to debug in the KJUR.jws.JWS.sign //4. sign portion of code.  Any insight?
Thanks

**Comment by iamrameshkr** [comment]
Search for this line in jws-3.0.js library.
         var mac = new KJUR.crypto.Mac({'alg': sigAlg, 'pass': hextorstr(key)});


Replace the target line with..
       var mac = new KJUR.crypto.Mac({'alg': sigAlg, 'pass':key});

It works for me. Hopefully same with you. 
Thanks

**Comment by davesbrown** [comment]
Thanks @iamrameshkr I was just thinking that was the problem while looking at that hextorstr function in the jsrsasign library last night.  Also, I found this https://github.com/kjur/jsjws/pull/18

Your quick solution fixed it for me.

**Comment by kjur** [comment]
I think issue was fixed in the latest release of jsrsasign 4.8.0 to which jsjws was merged. I'll close this ticket. regards,

**Comment by andyscott** [comment]
I am having this issue in jsrasign 4.8.3. I'm having to call `rstrtohex` on my key.

**Comment by kjur** [comment]
Shared secret for HMAC signatures shall be specified as hexadecimal string as described in the API document.
http://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.verify
