### ISSUE TITLE
bug : undefined variable

### ISSUE THREAD

**Issue by samvloeberghs** [kjur/jsjws#23]
You have a (very small ) bug in your code:

https://github.com/kjur/jsjws/blob/master/jws-3.0.js#L405-406

    if (! ns1.isSafeJSONString(sHeader))
	throw "JWS Head is not safe JSON string: " + sHead;

sHead should be sHeader?

Grtz

**Comment by kjur** [comment]
Hi @samvloeberghs , thank you for letting me know.
I'll fix it in next update which may be 3.2.1 or so.

**Comment by kjur** [comment]
Thank you for the report. I've fix and push the code. It'll be included in the next release. Thanks.
