### ISSUE TITLE
critical-vulnerabilities

### ISSUE THREAD

**Issue by adrai** [kjur/jsjws#25]
https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by davedoesdev** [comment]
@kjur You can find a patch you might find useful here: https://github.com/davedoesdev/node-jsjws/blob/master/patches/jsjws.patch

**Comment by pose** [comment]
@davedoesdev I've found something strange in your patch: https://github.com/davedoesdev/node-jsjws/blob/master/patches/jsjws.patch#L204 shouldn't be an `else` there? Thanks!

**Comment by davedoesdev** [comment]
@pose yes - although it doesn't affect the logic (do you agree?)

**Comment by pose** [comment]
@davedoesdev Yes, seems to be ok (the result should be the same). But it's better to be on the safe side :)

**Comment by davedoesdev** [comment]
Thanks @pose I appreciate you pointing it out. 
I've pushed the change and will publish a new version once the tests have run on node-jsjws.

**Comment by kjur** [comment]
I've removed alg=none support in the 'verify' method and released as 3.1.0 to resolve this issue. Thank you all.

**Comment by shea256** [comment]
So has this issue been completely resolved?

If so, can we update the "vulnerable" status on http://jwt.io/?

cc @pose @timmclean @cristiandouce

**Comment by pose** [comment]
@shea256: No. Although the issue is closed, it has not been 100% solved. @kjur is working on a fix for the algorithm confusion part. Thanks!

**Comment by kjur** [comment]
All, I've released jsjws 3.2.0 to mitigate the algorithm confusion issue that @pose have suggested. Thanks all of you discussed here.
