### ISSUE TITLE
No wiki - no tutorial

### ISSUE THREAD

**Issue by Upperstage** [kjur/jsjws#29]
The wiki appears to be empty and hence no tutorial

**Comment by kjur** [comment]
Please see samples, tools and test codes at this time.

**Comment by JaKXz** [comment]
+1 for a wiki / demo / some basic "hello world" usage of this library! It looks quite comprehensive and compliments for that, but it would be nice to know where to start.

**Comment by kjur** [comment]
The 'jsjws' have been merged into 'jsrsasign' 4.8.0 released today. Then JWS/JWT tutorial wiki pages are added.
https://github.com/kjur/jsrsasign/wiki
Regards,
