### ISSUE TITLE
Actual Security

### ISSUE THREAD

**Issue by tpharaoh** [kjur/jsjws#31]
Sorry for my ignorant question. But assuming I buld at HTML page using JSON/JSJWS. The values I want to encrypt are in the JSON, in the HTML.

So, I then encrypt before sending, so great, http traffic is encrypted. But, if someone looked at html source, wouldn't they see original values?

**Comment by kjur** [comment]
Sorry but jsjws/jsrsasign has now such functionality for JWE(JSON Web Encryption). Regards,
