### ISSUE TITLE
https !== http

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [kjur/jsjws#33]
# https !== http

> please update you resources!

**Comment by xgqfrms-GitHub** [comment]
https://kjur.github.io/jsjws/tool_b64udec.html
![https](https://cloud.githubusercontent.com/assets/18028768/26139392/e5aa03f0-3b02-11e7-8329-736e1c704a8a.png)

**Comment by kjur** [comment]
jsjws have been moved to jsrsasign and this page will not maintain any further.
Please see https://kjur.github.io/jsrsasign/tool/tool_b64udec.html
