### ISSUE TITLE
Redirect online tool pages to corresponding page on jsrsasign

### ISSUE THREAD

**Issue by franklinyu** [kjur/jsjws#35]
Currently I get the old site (http://kjur.github.io/jsjws/tool_b64udec.html) when searching "base64url decode" in Google. It would be greatly appreciated if visitor can be redirected from http://kjur.github.io/jsjws/tool_b64udec.html to http://kjur.github.io/jsrsasign/tool_b64udec.html now that the former is not maintained anymore.

**Comment by kjur** [comment]
jsjws site is end of support. Thanks.
